CREATE TABLE Newsletter (
	newsletterID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	fistName NVARCHAR(50) NOT NULL,
	lastName NVARCHAR(50) NOT NULL,
	email NVARCHAR(50) NOT NULL,
	comment NVARCHAR(100),
)

CREATE TABLE CreateYourTeam (
	teamID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	teamName NVARCHAR(50) NOT NULL,
)

CREATE TABLE Players (
	playerID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	fistName NVARCHAR(50) NOT NULL,
	lastName NVARCHAR(50) NOT NULL,
	teamID INT NOT NULL FOREIGN KEY REFERENCES CreateYourTeam(teamID),
)

CREATE TABLE Coaches (
	coachID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	firstName NVARCHAR(50) NOT NULL,
	lastName NVARCHAR(50) NOT NULL,
	teamID INT NOT NULL FOREIGN KEY REFERENCES CreateYourTeam(teamID),
)